spring:
  application:
    name: test-springBoot
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
